[package]
name = "random_numbers"
version = "0.0.1"
authors = ["markjunod <mark.junod@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
